"""empty message

Revision ID: 7c1bfe5b6125
Revises: 276c3187ea2b
Create Date: 2022-12-03 11:39:38.667087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c1bfe5b6125'
down_revision = '276c3187ea2b'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('artist_shows')
    
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('Show_venue_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('date')
        batch_op.drop_column('name')
        batch_op.drop_column('image_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Show_venue_id_fkey', 'Venue', ['venue_id'], ['id'])
        batch_op.drop_column('start_time')
        batch_op.drop_column('artist_id')

    op.create_table('artist_shows',
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='artist_shows_artist_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='artist_shows_show_id_fkey'),
    sa.PrimaryKeyConstraint('show_id', 'artist_id', name='artist_shows_pkey')
    )
    # ### end Alembic commands ###
