"""empty message

Revision ID: b9590e79218d
Revises: 7c1bfe5b6125
Create Date: 2022-12-03 13:27:02.807554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9590e79218d'
down_revision = '7c1bfe5b6125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_column('id')
        batch_op.drop_column('venue_id')
        batch_op.drop_column('artist_id')
        batch_op.drop_column('start_time')
    
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), primary_key=True))
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), primary_key=True))
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Show_id_seq"\'::regclass)'), autoincrement=True, nullable=False))

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=postgresql.ENUM('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', name='statesenum'),
               nullable=True)

    # ### end Alembic commands ###
