"""empty message

Revision ID: e3e5a298d757
Revises: 1386f8c68bfe
Create Date: 2022-11-27 11:49:00.578614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3e5a298d757'
down_revision = '1386f8c68bfe'
branch_labels = None
depends_on = None


def upgrade():
    genres_enum = postgresql.ENUM('Alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'HipHop', 'HeavyMetal', 'Instrumental', 'Jazz', 'MusicalTheatre', 'Pop', 'Punk', 'RB', 'Reggae', 'RocknRoll', 'Soul', 'Other', name='genres_enum')
    genres_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.Enum('Alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'HipHop', 'HeavyMetal', 'Instrumental', 'Jazz', 'MusicalTheatre', 'Pop', 'Punk', 'RB', 'Reggae', 'RocknRoll', 'Soul', 'Other', name='genres_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('genres')

    genres_enum = postgresql.ENUM('Alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'HipHop', 'HeavyMetal', 'Instrumental', 'Jazz', 'MusicalTheatre', 'Pop', 'Punk', 'RB', 'Reggae', 'RocknRoll', 'Soul', 'Other', name='genres_enum')
    genres_enum.drop(op.get_bind())
    # ### end Alembic commands ###
